<a href="https://colab.research.google.com/github/Guneetkaur001/Hoax-Chrome-Extension/blob/main/iOT_in_Agriculture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To choose the best soil for a crop, you need to consider several factors such as the type of crop, soil type, and soil nutrients . You can use linear regression to model the relationship between soil nutrients and crop yield. In your case, you have soil data with seven attributes: nitrogen (N), phosphorus pentoxide (P), potassium oxide (K), temperature, humidity, pH, and rainfall. You can use these attributes to predict the yield of different crops using linear regression .

To perform linear regression, you need to choose a dependent variable (y) that you want to predict based on the values of independent variables (x). In your case, you can choose crop yield as your dependent variable and the remaining six attributes as independent variables. Once you have chosen your dependent and independent variables, you can fit a linear regression model to your data using the `scikit-learn` library in Python .
Before applying linear regression, it's important to preprocess your data. You should check for missing values and outliers and remove them if necessary . You should also normalize your data to ensure that all variables are on the same scale . Once you have preprocessed your data, you can split it into training and testing sets. You can use the training set to fit a linear regression model and then use the testing set to evaluate the performance of your model .



In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv('/content/Crop_recommendation.csv')
data.head()

NameError: ignored

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [ ]:
#missing value sum
data.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [ ]:
#drop rows having missing values
data.dropna(axis=0)

,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice
...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,coffee
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,coffee
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,coffee
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,coffee


In [ ]:
#drop rows where data is null
data.dropna(axis= 0,how='any')

,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice
...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,coffee
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,coffee
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,coffee
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,coffee


In [ ]:
#drop rows which are completely null
data.dropna(axis=0, how='all')

,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice
...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,coffee
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,coffee
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,coffee
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,coffee


In [ ]:
x=data[['N',	'P',	'K',	'temperature',	'humidity',	'ph',	'rainfall']]  #feature
y= data['label']  #target
print(x.shape)
print(y.shape)

(2200, 7)
(2200,)


In [ ]:
type(x)

pandas.core.frame.DataFrame

In [ ]:
data ['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [ ]:
# can use the LabelEncoder class from the sklearn.preprocessing module
# to convert the string labels to integer values.

import pandas as pd
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['label'] = le.fit_transform(data['label'])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   int64  
dtypes: float64(4), int64(4)
memory usage: 137.6 KB


In [ ]:
#1 hot encoding
Label= pd.get_dummies(data["label"])
Label

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2196,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2197,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2198,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [ ]:
x=data.drop(['label'],axis =1)
y= data['label']
print(x)

        N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]


In [ ]:
y

0       20
1       20
2       20
3       20
4       20
        ..
2195     5
2196     5
2197     5
2198     5
2199     5
Name: label, Length: 2200, dtype: int64

In [ ]:
data.describe()

,N,P,K,temperature,humidity,ph,rainfall,label
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655,10.500000
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389,6.345731
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267,0.000000
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686,5.000000
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624,10.500000
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508,16.000000
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117,21.000000


In [ ]:
x.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117


data is normalized minmax scaling is appplied now it is scaled data

The MinMaxScaler scales the data to a fixed range of 0 to 1, which is useful when you have a bounded dataset. On the other hand, the StandardScaler scales the data to have a mean of 0 and a standard deviation of 1, which is useful when you have unbounded data. In the case of crop recommendation, the soil nutrient values are bounded between certain limits, so using MinMaxScaler is appropriate. However, if we are  have unbounded data, then using StandardScaler would be more appropriate.

In [ ]:
#FEATURE SCALING   -  minmax scaler
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler(feature_range=(0,1))# by default converts values between 0 to 1(feature range)


In [ ]:
x_minmax_scaled= minmax.fit_transform(x)
x_minmax_scaled

array([[0.64285714, 0.26428571, 0.19      , ..., 0.79026683, 0.46626364,
        0.65645778],
       [0.60714286, 0.37857143, 0.18      , ..., 0.77063285, 0.54948026,
        0.74167459],
       [0.42857143, 0.35714286, 0.195     , ..., 0.79397664, 0.67421877,
        0.87571039],
       ...,
       [0.84285714, 0.2       , 0.125     , ..., 0.61788046, 0.44443315,
        0.55007079],
       [0.83571429, 0.19285714, 0.145     , ..., 0.44175991, 0.50604494,
        0.38428046],
       [0.74285714, 0.09285714, 0.125     , ..., 0.53822177, 0.50931694,
        0.43372112]])

In [ ]:
pd.DataFrame(x_minmax_scaled).describe()

,0,1,2,3,4,5,6
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,0.361084,0.345448,0.215745,0.481798,0.667536,0.461053,0.299094
std,0.263695,0.235613,0.253240,0.145302,0.259716,0.120357,0.197444
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.150000,0.164286,0.075000,0.400108,0.536653,0.383641,0.159298
50%,0.264286,0.328571,0.135000,0.481294,0.772424,0.454143,0.268211
75%,0.601786,0.450000,0.220000,0.566315,0.882960,0.531681,0.373834
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000


HERE in descibe field we are now having min values as 0 and max as 1.

so now it is scaled data.

In [ ]:
y.value_counts()

20    100
11    100
8     100
6     100
4     100
17    100
16    100
0     100
15    100
21    100
7     100
12    100
1     100
19    100
10    100
2     100
14    100
13    100
18    100
9     100
3     100
5     100
Name: label, dtype: int64

it is a balanced datase

In [ ]:
type(x) # (2d array or a data frame nedded)
#[array-like ,sparse matrix] of shape (n_samples ,n_features)
#training data

pandas.core.frame.DataFrame

In [ ]:
type(y)   # array like of shape(n_samples) or (n_samples, n_targets)
# 1D or 2D both fine
#target values

pandas.core.series.Series

In [ ]:
x.shape

(2200, 7)

In [ ]:
y.shape

(2200,)

In [ ]:
#split  the data into train and test
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, train_size=0.5,random_state = 1)


In [ ]:
xtest

,N,P,K,temperature,humidity,ph,rainfall
1276,25,129,195,17.986678,81.177121,5.777271,72.371277
1446,106,20,51,29.730197,90.970157,6.342573,20.490356
335,33,59,22,22.642369,21.593961,5.947000,122.388601
1458,89,9,47,29.471563,90.770696,6.668383,28.752261
2038,62,49,37,24.217446,82.852840,7.479248,166.136589
...,...,...,...,...,...,...,...
742,28,68,19,34.638810,61.385979,7.699507,72.431691
1304,93,22,52,26.587407,81.325632,6.932740,41.875400
2058,89,57,43,26.915150,73.198975,6.998787,177.223305
1636,5,25,6,30.721199,94.013320,6.011302,106.811802


In [ ]:
xtrain

,N,P,K,temperature,humidity,ph,rainfall
1817,9,17,32,25.949517,93.405487,5.842318,172.054049
961,23,30,44,20.938929,85.429129,6.124761,103.029594
26,97,59,43,26.359272,84.044036,6.286500,271.358614
1388,110,21,54,26.736908,87.824302,6.747538,47.464470
1753,49,54,50,25.624466,93.182403,6.762522,97.263367
...,...,...,...,...,...,...,...
960,1,27,36,23.985988,93.342366,5.684995,104.991282
905,31,25,38,24.962732,92.405014,6.497367,109.416919
1096,92,81,52,28.010680,76.528081,5.891414,103.704078
235,28,58,81,17.475010,16.543148,6.180427,93.350343


In [ ]:
#build model

In [ ]:
##Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(xtrain,ytrain)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

Logistic regression is applied

In [ ]:
#test (prediction)
ypred = log.predict(xtest)
ypred

array([ 7, 15,  9, ...,  8, 16,  2])

In [ ]:
ytest.values

array([ 7, 15,  9, ...,  8, 16,  2])

In [ ]:
from sklearn.metrics import accuracy_score
score = accuracy_score(ytest,ypred)
score


0.9636363636363636

In [ ]:
#changing threshold value
#it's  scaled data

ypred_new = log.predict_proba(xtest)
ypred_new

array([[4.76797832e-005, 1.25034833e-065, 2.40235448e-096, ...,
        1.27919088e-062, 4.66699813e-124, 1.47194249e-100],
       [3.08678832e-061, 1.59804307e-031, 6.55056998e-053, ...,
        2.80492976e-038, 1.76976217e-051, 4.77203812e-007],
       [2.51412965e-032, 6.20068815e-010, 3.32867450e-009, ...,
        9.19119001e-028, 3.78677735e-011, 2.79912952e-044],
       ...,
       [2.15638667e-054, 3.04326603e-007, 3.39934222e-019, ...,
        2.63855809e-022, 3.74061285e-003, 1.46426136e-032],
       [1.89324326e-052, 7.77557683e-046, 5.94338829e-016, ...,
        2.88772603e-011, 1.05275366e-027, 1.16451723e-047],
       [4.00506607e-029, 7.88287630e-009, 9.86359796e-001, ...,
        2.05141683e-019, 2.59871238e-020, 1.01244861e-020]])

In [ ]:
threshold = 0.01
ypred_new = log.predict_proba(xtest)[:,1]
ypred_new= ypred_new >= threshold
ypred_new  =ypred_new.astype('int')
ypred_new

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
# value greater than threshold -> 1
# value smaller than threshold -> 0

In [ ]:
from sklearn.metrics import accuracy_score
score = accuracy_score(ytest,ypred_new)
score


0.09181818181818181

accucracy is less on changing threshold value.

cross validation

(ROC)Reciever Operating Characteristics

curve between true positive rate(tp/tp+fn) and false positive rate(fp/fp+tp)

at different threshhold values


**KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors =3 )
knn.fit(xtrain,ytrain)
ypred_knn = knn.predict(xtest)
ypred_knn


array([ 7, 15,  9, ...,  8, 16,  2])

In [ ]:
from sklearn.metrics import accuracy_score
score = accuracy_score(ytest,ypred_knn)
score

0.98

*MODEL EVALUATION OF CLASSIFICATION DATA*

**CONFUSION MATRIX**

(a) accuracy score

(b) precision score

(c) recall score

(d) F1= score

In [ ]:
from sklearn.metrics import recall_score, precision_score, f1_score

In [ ]:
recall = recall_score(ytest,ypred_knn)
precision= precision_score(ytest,ypred_knn, average='weighted')
f1= f1_score(ytest,ypred_knn, average='weighted')
print("Recall: ",recall)
print("Pricession: ",precision)
print("F1-Score: ",f1)

Recall:  0.98
Pricession:  0.9802758915783749
F1-Score:  0.9800163246804701


In [ ]:
from sklearn.metrics import roc_auc_score

In [ ]:
mypred = log.predict_proba(xtest)
mypred

array([[4.76797832e-005, 1.25034833e-065, 2.40235448e-096, ...,
        1.27919088e-062, 4.66699813e-124, 1.47194249e-100],
       [3.08678832e-061, 1.59804307e-031, 6.55056998e-053, ...,
        2.80492976e-038, 1.76976217e-051, 4.77203812e-007],
       [2.51412965e-032, 6.20068815e-010, 3.32867450e-009, ...,
        9.19119001e-028, 3.78677735e-011, 2.79912952e-044],
       ...,
       [2.15638667e-054, 3.04326603e-007, 3.39934222e-019, ...,
        2.63855809e-022, 3.74061285e-003, 1.46426136e-032],
       [1.89324326e-052, 7.77557683e-046, 5.94338829e-016, ...,
        2.88772603e-011, 1.05275366e-027, 1.16451723e-047],
       [4.00506607e-029, 7.88287630e-009, 9.86359796e-001, ...,
        2.05141683e-019, 2.59871238e-020, 1.01244861e-020]])

In [ ]:
fpr,tpr,thresholds = roc_curve(ytest,mypred)

ValueError: ignored

In [ ]:
roc_auc = roc_auc_score(ytest, log.predict_proba(xtest), multi_class='ovr')

In [ ]:
print('ROC AUC Score:', roc_auc)

ROC AUC Score: 0.9993189401813816


In [ ]:
from sklearn.metrics import roc_curve

In [ ]:
mypred = log.predict_proba(xtest)[:,1]
mypred

array([1.25034833e-65, 1.59804307e-31, 6.20068815e-10, ...,
       3.04326603e-07, 7.77557683e-46, 7.88287630e-09])

In [ ]:
fpr,tpr,thresholds = roc_curve(ytest,mypred)

In [ ]:
df =pd.DataFrame()
df['FPR'] =fpr
df['TPR']  = tpr
df['Threshold']  =threshold
df

NameError: ignored